name: schemake
description: Schemake (schema make) is a package for describing schemas from a declarative specification.
version: 0.6.8
repository: https://github.com/renatoathaydes/schemake

environment:
  sdk: ^3.1.1

dependencies:
  collection: ^1.18.0
  conveniently: ^1.2.0
  dart_casing: ^3.0.1

dev_dependencies:
  yaml: ^3.1.2
  lints: ^6.0.0
  test: ^1.21.0
  dartle: ^0.33.0
  path: ^1.8.3
